name: My Workflow
on: # Define the event(s) that trigger this workflow
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Allows manual triggering
jobs:
  my_job:
    runs-on: self-hosted # Specify the runner environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your code
      - name: Run a script
        run: echo "Hello from my job!"
      - name: Another step
        run: |
          echo "This is a multi-line script."
          echo "It can perform multiple commands."
